tasker_web/tasker/urls.py
from django.conf.urls import url
from tasker import views

urlpatterns = [
    url(r'^$', views.task_list, name='task_list'),
    url(r'^user/(?P<id>\d+)$', views.user_show, name='user_show'),
    url(r'^task/(?P<id>\d+)$', views.task_show, name='task_show'),
    url(r'^add_task$', views.add_task, name='add_task'),
    url(r'^add_subtask/(?P<id>\d+)$', views.add_subtask, name='add_subtask'),
    url(r'^repeat/(?P<id>\d+)$', views.repeat, name='repeat'),
    ]

tasker_web/tasker_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tasker.urls')),
]

tasker_web/tasker/models.py
from django.db import models

class Task(models.Model):
    name=models.CharField(max_length=256)
    execution_time=models.DateTimeField()

tasker_web/tasker/forms.py
from django import forms
import sys
sys.path.append('..')
from library import database

class TaskForm(forms.Form):
    name=forms.CharField()
    execute_time=forms.DateTimeField(required=False,
                                     input_formats=['%Y-%m-%dT%H:%M'],
                                     widget=forms.DateTimeInput(
                                        attrs={'type':"datetime-local",
                                               id:'execute_time'}))
    duration=forms.DurationField(required=False)
    tags=forms.CharField(required=False)
    priority=forms.IntegerField(required=False)
    shared_users=forms.CharField(required=False)
    completed=forms.BooleanField(required=False)

class RepeatForm(forms.Form):
    type=forms.ChoiceField(choices=((0, 'Interval'), (1, 'Weekdays'), (2, 'Dates')))
    when=forms.CharField(required=False)

tasker_web/tasker/views.py
import django
from django.shortcuts import render
from . import forms
import sys
sys.path.append('..')
from library import lib
from library import database
import tasker_web.settings as settings

def task_list(request):
    database.init_database(settings.DATABASE_FILE)
    tasks = database.load_tasks()
    tasks=[t for t in tasks if t.overtask is None]
    return render(request, 'tasker/task_list.html', {'tasks':tasks})

def task_show(request, id):
    id=int(id)
    database.init_database(settings.DATABASE_FILE)        
    if request.method=='POST':
        form=forms.TaskForm(request.POST)
        if form.is_valid():
            task=database.load_tasks(id=id)[0]
            task.name=form.cleaned_data['name']
            task.execute_time=form.cleaned_data['execute_time']
            task.duration=form.cleaned_data['duration']
            task.tags=form.cleaned_data['tags'].split()
            task.priority=form.cleaned_data['priority']
            task.shared_users=[(database.load_user(login=l))
                              for l in form.cleaned_data['shared_users'].split()]
            if not task.completed and form.cleaned_data['completed']:
                task.complete()
            if not form.cleaned_data['completed']:
                task.completed=False
            database.save_task(task)
            return django.shortcuts.redirect('/')
        else:
            return django.http.HttpResponse('Invalid data')
    else:
        task=database.load_tasks(id=id)[0]
        shared_users=' '.join([u.login for u in task.shared_users])
        form=forms.TaskForm(initial={'name':task.name, 
                                     'execute_time':task.execute_time.strftime('%Y-%m-%dT%H:%M')
                                        if task.execute_time is not None else '',
                                     'duration':task.duration,
                                     'tags':' '.join(task.tags),
                                     'priority':task.priority,
                                     'shared_users':shared_users,
                                     'completed':task.completed,
                                     })
        return render(request, 'tasker/task_show.html', {'form':form, 
                                                         'task':task})

def user_show(request, id):
    user=database.load_user(id=id)
    return render(request, 'tasker/user.html', {'user':user})

def add_task(request):
    task=lib.Task()
    database.save_task(task)
    return django.shortcuts.redirect('/task/%d' % task.id)

def add_subtask(request, id):
    task=lib.Task()
    overtask=database.load_tasks(id=id)[0]
    task.overtask=overtask
    database.save_task(task)
    return django.shortcuts.redirect('/task/%d' % task.id)

def repeat(request, id):
    database.init_database(settings.DATABASE_FILE)     
    if request.method=='GET':
        repeat=database.load_tasks(id=id)[0].repeat
        when=None
        if repeat.type==repeat.INTERVAL:
            when=str(repeat.when)
        else:
            when=' '.join([str(w) for w in repeat.when])
        form=forms.RepeatForm(initial={'type':repeat.type,
                                       'when':when})
        return render(request, 'tasker/repeat.html', {'repeat':repeat,
                                                      'form':form})
    else:
        form=forms.RepeatForm(request.POST)
        if form.is_valid():
            task=database.load_tasks(id=id)[0]
            
        else:
            return django.http.HttpResponse('Invalid data')

tasker_web/tasker/templates/tasker/Task.html
<div class="Task">
    <h3><a href="/task/{{task.id}}">{{ task.name }}</a></h3>
    {%if task.creator%} by 
        <a href="/user/{{task.creator.id}}">
            {{task.creator.login}}
        </a> 
        <br />
    {%endif%} 
    <!--{%if task.overtask%} is subtask of 
        <a href="/task/{{task.overtask.id}}">
            {{task.overtask.name}}
        </a> 
        <br />
    {%endif%}-->
    <div>
        {%if task.execute_time%} {{task.execute_time}} {%endif%}
        {%if task.duration%}, during {{task.duration}} {%endif%}
    </div>
    {%if task.completed%} Completed {%endif%}
    {%if task.subtasks%} Have subtasks {%endif%}
            
</div>

tasker_web/tasker/templates/tasker/TopMenu.html
<div class="TopMenu">
    <h2><a href="/">Tasker</a></h2>
</div>

tasker_web/tasker/templates/tasker/repeat.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style>
        {%include "tasker/TopMenuStyles.css"%}
    </style>
</head>
<body>
    {%include "tasker/TopMenu.html"%}
    {{form}}
</body>
</html>

tasker_web/tasker/templates/tasker/task_list.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="TaskStyles.css">
    <style>
    {%include "tasker/TaskStyles.css"%}
    {%include "tasker/TopMenuStyles.css"%}
    div.TaskList {
        width: 50%;
        margin: 0 auto;
    }

    </style>
</head>
<body>
    {%include "tasker/TopMenu.html"%}
    <div class="TaskList">
        <div class="Task" style="text-align:center">
            <h1><a href="/add_task">+</a></h1>
        </div>
        {%for task in tasks%}
            {%include "tasker/Task.html"%}
        {%endfor%}
    </div>
</body>
</html>

tasker_web/tasker/templates/tasker/task_show.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
    <style>
        form.TaskForm {
            background-color:khaki;
            padding:10px;
            border:3px solid red;
            border-radius:5px;
            position:relative;
            width:50%;
            margin: 10px auto;
        }
        {%include "tasker/TopMenuStyles.css"%}
        div.Field{
            margin: 5px;
        }
        #id_execute_time {
            line-height:inherit;
        }
        h3 {
            text-align: center;
            margin:auto;
        }
        {%include "tasker/TaskStyles.css"%}

        div.SubaskList {
            width: 50%;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    {%include "tasker/TopMenu.html"%}
    <form method="post" class="TaskForm">
        {% csrf_token %}
            <div class="Field">
                {%if overtask%} is subtask of 
                    <a href="/task/{{task.overtask.id}}">
                    {{task.overtask.name}}
                    </a> 
                    <br />
                {%endif%}
            </div>
            {%if task.repeat%} 
                Repeat  
                <a href="/repeat/{{task.id}}">
                    {{task.repeat}}
                </a> 
                <br />  
            {%endif%}
        {% for field in form %}
            <div class="Field">
                {{field.label}}:
                <div>{{field}}</div>
            </div>
        {%endfor%}
        <input type="submit" value="Save"/>
    </form>
    {%if task.subtasks%}
        <h3>Subtasks:</h3>
    {%endif%}
    <div class="SubaskList">
        {% for subtask in task.subtasks %}
            {%include "tasker/Task.html" with task=subtask%}
        {% endfor %}
        <div class="Task" style="text-align:center">
            <h1><a href="/add_subtask/{{task.id}}">+</a></h1>
        </div>
    </div>
</body>
</html>

tasker_web/tasker/templates/tasker/user.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style>
        div.TopMenu {
            height: auto;
            background-color: khaki;
            text-align: center;
            margin:auto;
            padding:10px;
            }

            div.TopMenu h2 {
                margin:auto;
            }
    </style>
</head>
<body>
    <div class="TopMenu">
        <h2>
            <a href="/">
                Tasker
            </a>
        </h2>
    </div>
    <h3>{{user.login}}</h3>

</body>
</html>